### ISSUE TITLE
DST with 5 Sundays (EU)

### ISSUE THREAD

**Issue by remcoNL** [G6EJD/ESP32-Time-Services-and-SETENV-variable#1]
The Daylight Savings are starting on the **last** Sunday of March in the EU. This is not always the 4th Sunday. For example, in 2019 March will have 5 Sundays, so DST will start on 31 of March, not on 24.

The problem now is that the DST will start one week to early if I select the 4th Sunday of the month. (M3.4).

**Comment by G6EJD** [comment]
You need to use M3.5 which is the last Sunday in March and do the same for DST off

**Comment by remcoNL** [comment]
That is great! Thank you so much.

 You might want to change your example as the same is true for [British DST:](https://www.timeanddate.com/time/change/uk/london)

`// Set timezone to British DST setenv("TZ","GMTGMT-1,M3.4.0/01,M10.4.0/02",1);`

**Comment by G6EJD** [comment]
Yes OK< for reference UK setting should be:

setenv("TZ", "GMT0BST,M3.5.0/01,M10.5.0/02",1);

The UK Is like the EU, we always use the last Sunday in the months of Mar and Oct so the 5 is essential to get that correct.
