### ISSUE TITLE
GPS and date

### ISSUE THREAD

**Issue by remcoNL** [G6EJD/ESP32-Time-Services-and-SETENV-variable#2]
Hi,

In your example you use `configTime(0, 0, "pool.ntp.org");` to obtain the date. In my project i get this info via GPS. Can i somehow 'feed' the date from GPS to the timerules?

thanks

**Comment by G6EJD** [comment]
If you can get UNIX time from the GPS then yes, you need to set the time to the ordinal time, then it all works OK,, but I think GPS does not provide UNIX/Ordinal Time, otherwise see here:

https://playground.arduino.cc/Code/Time

Scroll down and there is an example of using TinyGPS to get time.

**Comment by remcoNL** [comment]
Oooh, wait. I have to use TimeLib.h and not Time.h .....

Tx!
