### ISSUE TITLE
are these standard libaries

### ISSUE THREAD

**Issue by doanerock** [G6EJD/ESP32-Time-Services-and-SETENV-variable#4]
It looks like "WiFi.h" is https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFi.h
Is "time.h"  https://github.com/PaulStoffregen/Time/blob/master/Time.h ?
Please confirm or update.

**Comment by G6EJD** [comment]
Both built in now as far as I know, I’ll check and confirm. Definitely WiFi is part of the ESP32 core.

**Comment by G6EJD** [comment]
I have just confirmed no time library in my libraries folder and so its an in-built library.
https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/newlib/time.h

**Comment by G6EJD** [comment]
Time is in the same location too
