### ISSUE TITLE
A Problem of China Standard Time

### ISSUE THREAD

**Issue by GwnYn** [G6EJD/ESP32-Time-Services-and-SETENV-variable#5]
` // Set timezone to China Standard Time
  setenv("TZ", "CST-8CDT-9,M4.2.0/2,M9.2.0/3", 1);
  Serial.println("  CHINA Time  = "+printLocalTime());
  Serial.println();
  delay(2000);`
 
"CST-8CDT-9" should be "CST-8CDT-8"

**Comment by G6EJD** [comment]
I’ll amend it, but that code came from the POSIX database for China, so really a change request needs to be made to get that central record changed.
