### ISSUE TITLE
Local time seems to ignore BST

### ISSUE THREAD

**Issue by justoke** [G6EJD/ESP32-Time-Services-and-SETENV-variable#6]
I have been using the code shown on an esp32 and I assumed it was working, but since the BST change on March 29th it now appears obvious that the time is not adjusted as I expected. The time for local time is 1 hour behind. I'm in the UK.

This is a sample of the code. I've omitted all the Wifi setup code for the sake of brevity:

```
setup()
{
  //Configure time
  configTime(0, 0, "pool.ntp.org", "time.nist.gov");

  // See https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv for Timezone codes for your region
  setenv("TZ", "GMT0BST,M3.5.0/01,M10.5.0/02", 1);
//Noticed that some code examples include this line:
//tzset();
 
}

loop()
{
     Serial.println(getPrintLocalTime());
    delay(1000);
}

String time_str;
String getPrintLocalTime()
{
  struct tm timeinfo;
  if (!getLocalTime(&timeinfo))
  {
    Serial.println("Failed to obtain time");
    return "Time Error";
  }
  //See http://www.cplusplus.com/reference/ctime/strftime/
  char output[80];
  strftime(output, 80, "%d-%b-%y, %H:%M:%S", &timeinfo);
  time_str = String(output);
  return String(output);
}
```
My assumption was that once the TZ was configured that I would not have to supply the timezone offset or make any codes changes and the ESP32 would be able to keep time as the BST dates came around. The only thing I notice is that setenv is flagged as undefined in the VS Code ide, but code does compile.

Any advice would be appreciated.

**Comment by G6EJD** [comment]
Your code shoudl be:
configTime(gmtOffset_sec, daylightOffset_sec, ntpServer, "time.nist.gov"); //(gmtOffset_sec, daylightOffset_sec, ntpServer)
  setenv("TZ", Timezone, 1);  //setenv()adds the "TZ" variable to the environment with a value TimeZone, only used if set to 1, 0 means no change
  tzset(); // Set the TZ environment variable
  delay(100);
  bool TimeStatus = UpdateLocalTime();
  return TimeStatus;

where: 
int   gmtOffset_sec     = 0;    // UK normal time is GMT, so GMT Offset is 0, for US (-5Hrs) is typically -18000, AU is typically (+8hrs) 28800
int  daylightOffset_sec = 3600; // In the UK DST is +1hr or 3600-secs, other countries may use 2hrs 7200 or 30-mins 1800 or 5.5hrs 19800 Ahead of GMT use + offset behind - offset

**Comment by justoke** [comment]
Thank you for the prompt response and advice. That resolved it!

**Comment by G6EJD** [comment]
Good to hear it’s resolved now.
